{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf600
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red80\green80\blue80;\red236\green246\blue255;\red0\green0\blue0;
\red97\green84\blue161;\red43\green150\blue67;\red40\green109\blue175;}
{\*\expandedcolortbl;;\cssrgb\c38824\c38824\c38824;\cssrgb\c94118\c97255\c100000;\cssrgb\c0\c0\c0;
\cssrgb\c45882\c41961\c69412;\cssrgb\c19216\c63922\c32941;\cssrgb\c19216\c50980\c74118;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/\cf0 \
$ch = curl_init();\
\
curl_setopt($ch, CURLOPT_URL, \cf5 'https://api.sandbox.hyperwallet.com/rest/v3/users'\cf0 );\
curl_setopt($ch, CURLOPT_RETURNTRANSFER, \cf6 1\cf0 );\
curl_setopt($ch, CURLOPT_POSTFIELDS, \cf5 "\{ \\n      \\"profileType\\": \\"INDIVIDUAL\\",\\n      \\"programToken\\": \\"prg-0dc976a1-ce7f-43a6-9e2b-bff8afbe97e8\\"\\n   \}"\cf0 );\
curl_setopt($ch, CURLOPT_POST, \cf6 1\cf0 );\
curl_setopt($ch, CURLOPT_USERPWD, \cf5 'restapiuser@23373551615'\cf0  . \cf5 ':'\cf0  . \cf5 'Zxcvb12345'\cf0 );\
\
$headers = \cf7 array\cf0 ();\
$headers[] = \cf5 'Content-Type: application/json'\cf0 ;\
$headers[] = \cf5 'Accept: application/json'\cf0 ;\
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);\
\
$result = curl_exec($ch);\
\cf7 if\cf0  (curl_errno($ch)) \{\
    \cf7 echo\cf0  \cf5 'Error:'\cf0  . curl_error($ch);\
\}\
curl_close($ch);}